### ISSUE TITLE
Operator upgrades from 2.0.x -> 2.1.x fail on restart

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1173]
If user has `2.0.x` installed and upgrades to `2.1.3`, then pod restarts or upgrades to `2.1.4` will fail as the `2.1.3` pods can't start again due to corrupt SFS data.

```
2021-06-23 07:59:06,079 WARN  [io.qua.qut.run.ContentTypes] (main) Unable to detect the content type for templates/jgroups-encrypt; using application/octet-stream
2021-06-23 07:59:06,107 INFO  [io.quarkus] (main) config-generator 2.1.4.Final-redhat-00001 on JVM (powered by Quarkus 1.7.6.Final-redhat-00015) started in 0.545s.
2021-06-23 07:59:06,108 INFO  [io.quarkus] (main) Profile prod activated.
2021-06-23 07:59:06,108 INFO  [io.quarkus] (main) Installed features: [cdi, qute]
2021-06-23 07:59:06,677 INFO  [io.quarkus] (main) config-generator stopped in 0.002s

07:59:07,964 INFO  (main) [BOOT] JVM OpenJDK 64-Bit Server VM Red Hat, Inc. 11.0.11+9-LTS
07:59:07,971 INFO  (main) [BOOT] JVM arguments = [-server, -Xmx512m, -XX:+ExitOnOutOfMemoryError, -XX:MetaspaceSize=32m, -XX:MaxMetaspaceSize=96m, -Djava.net.preferIPv4Stack=true, -Djava.awt.headless=true, -Dvisualvm.display.name=redhat-datagrid-server, -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager, -Dinfinispan.server.home.path=/opt/infinispan, -classpath, :/opt/infinispan/boot/infinispan-server-runtime-12.1.3.Final-redhat-00001-loader.jar, org.infinispan.server.loader.Loader, org.infinispan.server.Bootstrap]
07:59:07,971 INFO  (main) [BOOT] PID = 97
07:59:07,997 INFO  (main) [org.infinispan.SERVER] ISPN080000: Red Hat Data Grid Server starting
07:59:07,997 INFO  (main) [org.infinispan.SERVER] ISPN080017: Server configuration: infinispan.xml
07:59:07,997 INFO  (main) [org.infinispan.SERVER] ISPN080032: Logging configuration: /opt/infinispan/server/conf/log4j2.xml
07:59:09,063 INFO  (main) [org.wildfly.openssl.SSL] WFOPENSSL0002 OpenSSL Version OpenSSL 1.1.1g FIPS  21 Apr 2020
07:59:09,064 INFO  (main) [org.infinispan.SECURITY] ISPN000946: Using OpenSSL Provider
07:59:09,320 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'query-dsl-filter-converter-factory'
07:59:09,320 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'continuous-query-filter-converter-factory'
07:59:09,330 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'iteration-filter-converter-factory'
07:59:09,331 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'jdk.nashorn.api.scripting.NashornScriptEngineFactory'
07:59:09,800 INFO  (main) [org.infinispan.CONTAINER] ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
07:59:10,159 WARN  (main) [org.infinispan.PERSISTENCE] ISPN000554: jboss-marshalling is deprecated and planned for removal
07:59:10,777 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.protobuf.TimestampSchemaImpl
07:59:10,777 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.protobuf.EmptySchemaImpl
07:59:10,777 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.java.CommonTypesSchema
07:59:10,778 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.protobuf.DurationSchemaImpl
07:59:10,778 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.protobuf.AnySchemaImpl
07:59:10,779 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.protobuf.WrappersSchemaImpl
07:59:10,779 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.protostream.types.java.CommonContainerTypesSchema
07:59:10,780 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.query.core.stats.impl.PersistenceContextInitializerImpl
07:59:10,781 INFO  (main) [org.infinispan.CONTAINER] ISPN000128: Infinispan version: Red Hat Data Grid 'Infinispan 12.1.3.Final-redhat-00001' 8.2.0.GA
07:59:10,782 INFO  (main) [org.infinispan.CONTAINER] ISPN000389: Loaded global state, version=12.1.3.Final-redhat-00001 timestamp=2021-06-23T07:57:39.477081Z
07:59:10,984 INFO  (main) [org.infinispan.CLUSTER] ISPN000078: Starting JGroups channel infinispan with stack image-tcp
07:59:11,071 WARN  (main) [org.jgroups.stack.Configurator] JGRP000014: STABLE.stability_delay has been deprecated: always 0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.infinispan.commons.util.Util (file:/opt/infinispan/lib/infinispan-commons-12.1.3.Final-redhat-00001.jar) to constructor com.sun.jndi.dns.DnsContextFactory()
WARNING: Please consider reporting this to the maintainers of org.infinispan.commons.util.Util
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
07:59:13,164 INFO  (main) [org.infinispan.CLUSTER] ISPN000094: Received new cluster view for channel infinispan: [infinispan-0-13065|0] (1) [infinispan-0-13065]
07:59:13,169 INFO  (main) [org.infinispan.CLUSTER] ISPN000079: Channel infinispan local address is infinispan-0-13065, physical addresses are [10.128.2.50:7800]
07:59:13,484 INFO  (main) [org.jboss.threads] JBoss Threads version 2.3.3.Final-redhat-00001
07:59:13,522 INFO  (main) [org.infinispan.CLUSTER] ISPN000080: Disconnecting JGroups channel infinispan
07:59:13,528 INFO  (main) [org.infinispan.CONTAINER] ISPN000390: Persisted state, version=12.1.3.Final-redhat-00001 timestamp=2021-06-23T07:59:13.527820Z
07:59:13,553 INFO  (main) [org.infinispan.server.core.RequestTracer] OpenTracing integration is disabled
07:59:13,554 FATAL (main) [org.infinispan.SERVER] ISPN080028: Red Hat Data Grid Server failed to start java.util.concurrent.ExecutionException: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.persistence.manager.PersistenceManager
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:160)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.infinispan.server.loader.Loader.run(Loader.java:106)
	at org.infinispan.server.loader.Loader.main(Loader.java:51)
Caused by: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.persistence.manager.PersistenceManager
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:752)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:718)
	at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:67)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:39)
	at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:70)
	at org.infinispan.server.Server.run(Server.java:355)
	... 9 more
Caused by: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.persistence.manager.PersistenceManager
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:572)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:622)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:586)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:564)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:622)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:586)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:564)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:622)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:586)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:564)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:622)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:586)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:564)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:354)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:213)
	at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:1015)
	at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:512)
	at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:698)
	at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:644)
	at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:533)
	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:511)
	at org.infinispan.security.actions.GetCacheAction.run(GetCacheAction.java:26)
	at org.infinispan.security.actions.GetCacheAction.run(GetCacheAction.java:14)
	at org.infinispan.security.Security.doPrivileged(Security.java:61)
	at org.infinispan.globalstate.impl.SecurityActions.doPrivileged(SecurityActions.java:30)
	at org.infinispan.globalstate.impl.SecurityActions.getCache(SecurityActions.java:39)
	at org.infinispan.globalstate.impl.GlobalConfigurationManagerImpl.start(GlobalConfigurationManagerImpl.java:94)
	at org.infinispan.globalstate.impl.CorePackageImpl$2.start(CorePackageImpl.java:59)
	at org.infinispan.globalstate.impl.CorePackageImpl$2.start(CorePackageImpl.java:48)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:604)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:595)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:564)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:354)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:747)
	... 15 more
Caused by: java.util.concurrent.CompletionException: org.infinispan.persistence.spi.PersistenceException: ISPN000279: Failed to read stored entries from file. Error in file /opt/infinispan/server/data/___event_log_cache.dat at offset 273
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.infinispan.persistence.spi.PersistenceException: ISPN000279: Failed to read stored entries from file. Error in file /opt/infinispan/server/data/___event_log_cache.dat at offset 273
	at org.infinispan.persistence.file.SingleFileStore.rebuildIndex(SingleFileStore.java:237)
	at org.infinispan.persistence.file.SingleFileStore.start(SingleFileStore.java:163)
	at org.infinispan.persistence.support.NonBlockingStoreAdapter.lambda$start$0(NonBlockingStoreAdapter.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 5 more

07:59:13,558 INFO  (Thread-1) [org.infinispan.SERVER] ISPN080002: Red Hat Data Grid Server stopping
07:59:13,559 INFO  (Thread-1) [org.infinispan.SERVER] ISPN080003: Red Hat Data Grid Server stopped
```

The root cause of the SFS corruption is [ISPN-13116](https://issues.redhat.com/browse/ISPN-13116), which requires a fix on the server side in order to recover corrupt data. It's also necessary for the latest operator to be updated so that the failing pods don't prevent the upgrade from proceeding during graceful shutdown.

**Comment by ryanemerson** [comment]
Closing fixed in Operator 2.1.5
