### ISSUE TITLE
XSite tests flaky

### ISSUE THREAD

**Issue by gustavonalle** [infinispan/infinispan-operator#1234]
There is failures in master and in some PRs, with this random failure:

```
+ go test -v ./test/e2e/xsite/ -timeout 30m
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.IPBlock
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicy
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicyEgressRule
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicyIngressRule
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicyList
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicyPeer
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicyPort
13:52:58  2021/08/10 08:52:57 proto: duplicate proto type registered: k8s.io.api.networking.v1.NetworkPolicySpec
13:52:58  === RUN   TestCrossSiteViewInternal
13:54:29  --- PASS: TestCrossSiteViewInternal (90.13s)
13:54:29  === RUN   TestCrossSiteViewKubernetesNodePort
13:56:16  --- PASS: TestCrossSiteViewKubernetesNodePort (94.16s)
13:56:16  === RUN   TestCrossSiteViewOpenshiftNodePort
13:57:33  --- PASS: TestCrossSiteViewOpenshiftNodePort (82.20s)
13:57:33  === RUN   TestCrossSiteViewKubernetesLoadBalancer
14:02:40  --- FAIL: TestCrossSiteViewKubernetesLoadBalancer (304.30s)
14:02:40  panic: timed out waiting for the condition [recovered]
14:02:40  	panic: timed out waiting for the condition [recovered]
14:02:40  	panic: timed out waiting for the condition [recovered]
14:02:40  	panic: timed out waiting for the condition
14:02:40  
14:02:40  goroutine 1147 [running]:
14:02:40  testing.tRunner.func1.1(0x160b7e0, 0xc00062ced0)
14:02:40  	/usr/lib/golang/src/testing/testing.go:1072 +0x30d
14:02:40  testing.tRunner.func1(0xc00091b380)
14:02:40  	/usr/lib/golang/src/testing/testing.go:1075 +0x41a
14:02:40  panic(0x160b7e0, 0xc00062ced0)
14:02:40  	/usr/lib/golang/src/runtime/panic.go:969 +0x1b9
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.CleanNamespaceAndLogOnPanic(0xc000944d20, 0xc000048072, 0x15, 0xc000976690)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/utils/kubernetes.go:192 +0xf85
14:02:40  panic(0x160b7e0, 0xc00062ced0)
14:02:40  	/usr/lib/golang/src/runtime/panic.go:969 +0x1b9
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.CleanNamespaceAndLogOnPanic(0xc000951800, 0xc000048072, 0x15, 0xc0009766c0)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/utils/kubernetes.go:192 +0xf85
14:02:40  panic(0x160b7e0, 0xc00062ced0)
14:02:40  	/usr/lib/golang/src/runtime/panic.go:969 +0x1b9
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/utils.ExpectNoError(...)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/utils/asserts.go:27
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.WaitForPods(0xc000944d20, 0x2, 0x45d964b800, 0xc00050ee60, 0x0)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/utils/kubernetes.go:533 +0xff
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.WaitForInfinispanPods(0xc000944d20, 0x2, 0x45d964b800, 0xc000908a00, 0x34, 0xc0006117c0, 0x1c)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/utils/kubernetes.go:495 +0x23e
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/xsite.testCrossSiteView(0xc00091b380, 0x61127701, 0x1847ca1, 0xa, 0x18496b0, 0xc, 0xb532c00000000)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/xsite/xsite_test.go:183 +0xcd2
14:02:40  github.com/infinispan/infinispan-operator/test/e2e/xsite.TestCrossSiteViewKubernetesLoadBalancer(0xc00091b380)
14:02:40  	/home/infinispan/workspace/Infinispan_Operator_main/test/e2e/xsite/xsite_test.go:117 +0x65
14:02:40  testing.tRunner(0xc00091b380, 0x19002d8)
14:02:40  	/usr/lib/golang/src/testing/testing.go:1123 +0xef
14:02:40  created by testing.(*T).Run
14:02:40  	/usr/lib/golang/src/testing/testing.go:1168 +0x2b3
14:02:40  FAIL	github.com/infinispan/infinispan-operator/test/e2e/xsite	570.844s
```

**Comment by dmvolod** [comment]
@gustavonalle seems to something happens with xsite clusters pre-setup
