### ISSUE TITLE
GracefulShutdownTask should only shutdown user caches

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1255]
Currently `GracefulShutdownTask` attempts to shutdown all caches on the server, however in some scenarios this can result in the `___protobuf_metadata` and `___script_cache` timing out on CacheJoin after a restart.

```
10:00:42,996 ERROR (non-blocking-thread--p2-t2) [org.infinispan.topology.ClusterCacheStatus] ISPN000228: Failed to recover cache ___protobuf_metadata state after the current node became the coordinator org.infinispan.topology.CacheJoinException: ISPN000408: Node test-upgrade-1-17904 with persistent state attempting to join cache ___protobuf_metadata on cluster without state
	at org.infinispan.topology.ClusterCacheStatus.addMember(ClusterCacheStatus.java:237)
	at org.infinispan.topology.ClusterCacheStatus.addMembers(ClusterCacheStatus.java:690)
	at org.infinispan.topology.ClusterCacheStatus.recoverMembers(ClusterCacheStatus.java:670)
	at org.infinispan.topology.ClusterCacheStatus.doMergePartitions(ClusterCacheStatus.java:648)
	at org.infinispan.topology.ClusterTopologyManagerImpl.lambda$recoverClusterStatus$7(ClusterTopologyManagerImpl.java:434)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at org.infinispan.executors.LimitedExecutor.actualRun(LimitedExecutor.java:192)
	at org.infinispan.executors.LimitedExecutor.runTasks(LimitedExecutor.java:176)
	at org.infinispan.executors.LimitedExecutor.access$100(LimitedExecutor.java:38)
	at org.infinispan.executors.LimitedExecutor$Runner.run(LimitedExecutor.java:237)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:829)

10:00:43,000 INFO  (non-blocking-thread--p2-t2) [org.infinispan.CLUSTER] [Context=batch-cache]ISPN100007: After merge (or coordinator change), recovered members [test-upgrade-1-17904] with topology id 7
10:00:43,089 INFO  (non-blocking-thread--p2-t2) [org.infinispan.CLUSTER] [Context=org.infinispan.COUNTER]ISPN100007: After merge (or coordinator change), recovered members [test-upgrade-1-17904] with topology id 7
10:00:43,092 ERROR (non-blocking-thread--p2-t2) [org.infinispan.topology.ClusterCacheStatus] ISPN000228: Failed to recover cache ___script_cache state after the current node became the coordinator org.infinispan.topology.CacheJoinException: ISPN000408: Node test-upgrade-1-17904 with persistent state attempting to join cache ___script_cache on cluster without state
	at org.infinispan.topology.ClusterCacheStatus.addMember(ClusterCacheStatus.java:237)
	at org.infinispan.topology.ClusterCacheStatus.addMembers(ClusterCacheStatus.java:690)
	at org.infinispan.topology.ClusterCacheStatus.recoverMembers(ClusterCacheStatus.java:670)
	at org.infinispan.topology.ClusterCacheStatus.doMergePartitions(ClusterCacheStatus.java:648)
	at org.infinispan.topology.ClusterTopologyManagerImpl.lambda$recoverClusterStatus$7(ClusterTopologyManagerImpl.java:434)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at org.infinispan.executors.LimitedExecutor.actualRun(LimitedExecutor.java:192)
	at org.infinispan.executors.LimitedExecutor.runTasks(LimitedExecutor.java:176)
	at org.infinispan.executors.LimitedExecutor.access$100(LimitedExecutor.java:38)
	at org.infinispan.executors.LimitedExecutor$Runner.run(LimitedExecutor.java:237)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The underlying issue needs to be fixed on the Infinispan server [ISPN-13226](https://issues.redhat.com/browse/ISPN-13226). Until then, it's necessary for the `GracefulShutdownTask` to be updated to only shutdown user caches, in the same manner as the Infinispan server.

**Comment by prashankjauhari** [comment]
it it fixed?

**Comment by ryanemerson** [comment]
The GracefulShutdownTask has been removed in 2.3.2 and we plan to release this by the end of the week.

Previously the GracefulShutdownTask was only used if the initial server shutdown operation was not supported (Operands older than Infinispan 13) or if it failed unexpectedly, so if you're using the latest Operator release this should not be of concern.
