### ISSUE TITLE
Server startup fails on Openshift with encryption type service

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1563]
Operator `main` fails on Openshift with encryption `type=service`

```
example-infinispan-0 infinispan 16:15:22,834 FATAL (main) [org.infinispan.SERVER] ISPN080028: Infinispan Server failed to start org.infinispan.commons.CacheConfigurationException: java.io.FileNotFoundException: /etc/security/conf/operator-security/keystore.pem (No such file or directory)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.KeyStoreConfiguration.build(KeyStoreConfiguration.java:83)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.SSLConfiguration.build(SSLConfiguration.java:39)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.RealmConfiguration.init(RealmConfiguration.java:111)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.RealmsConfiguration.init(RealmsConfiguration.java:33)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.SecurityConfiguration.<init>(SecurityConfiguration.java:17)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.SecurityConfigurationBuilder.create(SecurityConfigurationBuilder.java:37)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.ServerConfigurationBuilder.create(ServerConfigurationBuilder.java:70)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.ServerConfigurationBuilder.create(ServerConfigurationBuilder.java:21)
example-infinispan-0 infinispan 	at org.infinispan.configuration.global.GlobalConfigurationBuilder.build(GlobalConfigurationBuilder.java:267)
example-infinispan-0 infinispan 	at org.infinispan.configuration.ConfigurationManager.<init>(ConfigurationManager.java:39)
example-infinispan-0 infinispan 	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:375)
example-infinispan-0 infinispan 	at org.infinispan.server.Server.run(Server.java:382)
example-infinispan-0 infinispan 	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:165)
example-infinispan-0 infinispan 	at org.infinispan.server.tool.Main.run(Main.java:98)
example-infinispan-0 infinispan 	at org.infinispan.server.Bootstrap.main(Bootstrap.java:50)
example-infinispan-0 infinispan 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
example-infinispan-0 infinispan 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
example-infinispan-0 infinispan 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
example-infinispan-0 infinispan 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
example-infinispan-0 infinispan 	at org.infinispan.server.loader.Loader.run(Loader.java:106)
example-infinispan-0 infinispan 	at org.infinispan.server.loader.Loader.main(Loader.java:51)
example-infinispan-0 infinispan Caused by: java.io.FileNotFoundException: /etc/security/conf/operator-security/keystore.pem (No such file or directory)
example-infinispan-0 infinispan 	at java.base/java.io.FileInputStream.open0(Native Method)
example-infinispan-0 infinispan 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
example-infinispan-0 infinispan 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
example-infinispan-0 infinispan 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.KeyStoreConfiguration.buildKeyStore(KeyStoreConfiguration.java:100)
example-infinispan-0 infinispan 	at org.infinispan.server.configuration.security.KeyStoreConfiguration.build(KeyStoreConfiguration.java:67)
example-infinispan-0 infinispan 	... 20 more
example-infinispan-0 infinispan 

```

**Comment by ryanemerson** [comment]
Duplicates #1587
