### ISSUE TITLE
Server pods are unable to find certificates provided by OpenShift

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-operator#1587]
Only affects `main`
```
14:44:10,401 INFO  (main) [BOOT] JVM OpenJDK 64-Bit Server VM Red Hat, Inc. 17.0.3+7-LTS
14:44:10,405 INFO  (main) [BOOT] JVM arguments = [-server, --add-exports, java.naming/com.sun.jndi.ldap=ALL-UNNAMED, -Xmx512m, -XX:+ExitOnOutOfMemoryError, -XX:MetaspaceSize=32m, -XX:MaxMetaspaceSize=96m, -Djava.net.preferIPv4Stack=true, -Djava.awt.headless=true, -Dvisualvm.display.name=redhat-datagrid-server, -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager, -Dinfinispan.server.home.path=/opt/infinispan, -classpath, :/opt/infinispan/boot/infinispan-server-runtime-14.0.0.Final-temporary-redhat-00018-loader.jar, org.infinispan.server.loader.Loader, org.infinispan.server.Bootstrap, --bind-address=0.0.0.0, -l, /opt/infinispan/server/conf/operator/log4j.xml, -c, operator/infinispan.xml]
14:44:10,407 INFO  (main) [BOOT] PID = 127
14:44:10,428 INFO  (main) [org.infinispan.SERVER] ISPN080000: Red Hat Data Grid Server 8.4.0.GA starting
14:44:10,428 INFO  (main) [org.infinispan.SERVER] ISPN080017: Server configuration: operator/infinispan.xml
14:44:10,428 INFO  (main) [org.infinispan.SERVER] ISPN080032: Logging configuration: /opt/infinispan/server/conf/operator/log4j.xml
14:44:10,689 WARN  (main) [org.infinispan.CONFIG] ISPN000653: The 'keystore-password' attribute on the 'keystore' element has been deprecated. Please use the 'password' attribute instead
14:44:10,745 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'query-dsl-filter-converter-factory'
14:44:10,745 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'continuous-query-filter-converter-factory'
14:44:10,747 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'iteration-filter-converter-factory'
14:44:10,747 WARN  (main) [org.infinispan.SERVER] ISPN080059: No script engines are available
14:44:10,749 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'org.infinispan.example.HelloTask01'
14:44:10,749 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'org.infinispan.example.HelloTask02'
14:44:10,805 INFO  (main) [org.wildfly.openssl.SSL] WFOPENSSL0002 OpenSSL Version OpenSSL 1.1.1k  FIPS 25 Mar 2021
14:44:10,805 INFO  (main) [org.infinispan.SECURITY] ISPN000946: Using OpenSSL Provider
14:44:10,806 FATAL (main) [org.infinispan.SERVER] ISPN080028: Red Hat Data Grid Server failed to start org.infinispan.commons.CacheConfigurationException: java.io.FileNotFoundException: /etc/security/conf/operator-security/keystore.pem (No such file or directory)
	at org.infinispan.server.configuration.security.KeyStoreConfiguration.build(KeyStoreConfiguration.java:85)
	at org.infinispan.server.configuration.security.SSLConfiguration.build(SSLConfiguration.java:39)
	at org.infinispan.server.configuration.security.RealmConfiguration.init(RealmConfiguration.java:111)
	at org.infinispan.server.configuration.security.RealmsConfiguration.init(RealmsConfiguration.java:33)
	at org.infinispan.server.configuration.security.SecurityConfiguration.<init>(SecurityConfiguration.java:17)
	at org.infinispan.server.configuration.security.SecurityConfigurationBuilder.create(SecurityConfigurationBuilder.java:37)
	at org.infinispan.server.configuration.ServerConfigurationBuilder.create(ServerConfigurationBuilder.java:72)
	at org.infinispan.server.configuration.ServerConfigurationBuilder.create(ServerConfigurationBuilder.java:21)
	at org.infinispan.configuration.global.GlobalConfigurationBuilder.build(GlobalConfigurationBuilder.java:267)
	at org.infinispan.configuration.ConfigurationManager.<init>(ConfigurationManager.java:39)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:376)
	at org.infinispan.server.Server.run(Server.java:393)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:168)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.infinispan.server.loader.Loader.run(Loader.java:106)
	at org.infinispan.server.loader.Loader.main(Loader.java:51)
Caused by: java.io.FileNotFoundException: /etc/security/conf/operator-security/keystore.pem (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at org.infinispan.server.configuration.security.KeyStoreConfiguration.buildKeyStore(KeyStoreConfiguration.java:102)
	at org.infinispan.server.configuration.security.KeyStoreConfiguration.build(KeyStoreConfiguration.java:69)
	... 20 more

null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.infinispan.server.loader.Loader.run(Loader.java:106)
	at org.infinispan.server.loader.Loader.main(Loader.java:51)
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.infinispan.manager.EmbeddedCacheManager.getStatus()" because "cacheManager" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
	at org.infinispan.server.Server.run(Server.java:485)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:168)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:50)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.infinispan.manager.EmbeddedCacheManager.getStatus()" because "cacheManager" is null
	at org.infinispan.server.SecurityActions.lambda$stopCacheManager$2(SecurityActions.java:76)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:40)
	at org.infinispan.server.SecurityActions.stopCacheManager(SecurityActions.java:83)
	at org.infinispan.server.Server.localShutdown(Server.java:579)
	at org.infinispan.server.Server.lambda$run$4(Server.java:489)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	... 12 more
```

**Comment by ryanemerson** [comment]
This also affects 2.2.x as webhooks have been backported
