### ISSUE TITLE
Random "curl: (52) Empty reply from server" error when creating a cache

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#257]
[Example](https://travis-ci.org/infinispan/infinispan-operator/jobs/636855778#L1580).

The creation of the default cache fails:

```
{"level":"error","ts":1579005228.9610772,"logger":"controller_infinispan"
,"msg":"failed to create default cache for cache service"
,"Request.Namespace":"namespace-for-testing","Request.Name":"test-cache-service"
,"error":"unexpected error creating cache, stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   452    0     0  100   452      0   4346 --:--:-- --:--:-- --:--:--  4304\r100   452    0     0  100   452      0   4304 --:--:-- --:--:-- --:--:--  4264\ncurl: (52) Empty reply from server\n, err: command terminated with exit code 52"
,"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/infinispan/infinispan-operator/pkg/controller/infinispan.(*ReconcileInfinispan).Reconcile\n\t/home/travis/gopath/src/github.com/infinispan/infinispan-operator/pkg/controller/infinispan/infinispan_controller.go:498\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.8/pkg/internal/controller/controller.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.8/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}
```

And so the test fails when using it:

```
panic: unexpected HTTP status code (404): ISPN012010: Cache with name 'default' not found amongst the configured caches [recovered]
	panic: unexpected HTTP status code (404): ISPN012010: Cache with name 'default' not found amongst the configured caches
goroutine 7658 [running]:
testing.tRunner.func1(0xc00099a900)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/testing/testing.go:874 +0x3a3
panic(0x120de20, 0xc0002f6390)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/infinispan/infinispan-operator/test/e2e.throwHttpError(0xc00028e510)
	/home/travis/gopath/src/github.com/infinispan/infinispan-operator/test/e2e/main_test.go:694 +0x189
github.com/infinispan/infinispan-operator/test/e2e.putViaRoute(0xc0000fe000, 0x32, 0x13a5336, 0xd, 0xc000805590, 0x13a190c, 0x9, 0xc0008dc1c0, 0x10)
	/home/travis/gopath/src/github.com/infinispan/infinispan-operator/test/e2e/main_test.go:688 +0x2f0
github.com/infinispan/infinispan-operator/test/e2e.TestCacheService(0xc00099a900)
	/home/travis/gopath/src/github.com/infinispan/infinispan-operator/test/e2e/main_test.go:247 +0x563
testing.tRunner(0xc00099a900, 0x142c5d8)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/testing/testing.go:960 +0x350
FAIL	github.com/infinispan/infinispan-operator/test/e2e	933.918s
```

**Comment by dmvolod** [comment]
@galderz looks like fix #280 is resolved this issue
