### ISSUE TITLE
Random "curl: (16) Error in the HTTP2 framing layer" when getting cluster members

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-operator#259]
[Example](https://travis-ci.org/infinispan/infinispan-operator/jobs/636855778?utm_medium=notification&utm_source=github_status)

```
--- FAIL: TestClusterFormationWithTLS (392.49s)
panic: timed out waiting for the condition, last error: unexpected error getting cluster members, stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (16) Error in the HTTP2 framing layer
, err: command terminated with exit code 16 [recovered]
	panic: timed out waiting for the condition, last error: unexpected error getting cluster members, stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (16) Error in the HTTP2 framing layer
, err: command terminated with exit code 16
goroutine 2710 [running]:
testing.tRunner.func1(0xc000253e00)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/testing/testing.go:874 +0x3a3
panic(0x11c4760, 0xc000709340)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/infinispan/infinispan-operator/test/e2e/util.ExpectNoError(...)
	/home/travis/gopath/src/github.com/infinispan/infinispan-operator/test/e2e/util/asserts.go:8
github.com/infinispan/infinispan-operator/test/e2e.waitForPodsOrFail(0xc00019f000, 0x139f307, 0x5, 0x2)
	/home/travis/gopath/src/github.com/infinispan/infinispan-operator/test/e2e/main_test.go:404 +0x2e4
github.com/infinispan/infinispan-operator/test/e2e.TestClusterFormationWithTLS(0xc000253e00)
	/home/travis/gopath/src/github.com/infinispan/infinispan-operator/test/e2e/main_test.go:123 +0x20a
testing.tRunner(0xc000253e00, 0x142c5e8)
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.13.6.linux.amd64/src/testing/testing.go:960 +0x350
FAIL	github.com/infinispan/infinispan-operator/test/e2e	630.229s
```

**Comment by dmvolod** [comment]
@galderz looks like fix #280 is resolved this issue
