### ISSUE TITLE
Cannot 'oc port-forward' into an operator deployed cluster

### ISSUE THREAD

**Issue by j1cken** [infinispan/infinispan-operator#464]
Trying to

```
oc port-forward svc/datagrid 11222
```

 into a running datagrid cluster (DataGrid Operator 8.0.1) on OpenShift results in

```
E0708 18:53:03.265914   43134 portforward.go:400] an error occurred forwarding 11222 -> 11222: error forwarding port 11222 to pod 2c34cfaa23efba1506d81ae31143d9debc8339b237ae200d0bd05a27de2556bb, uid : exit status 1: 2020/07/08 16:53:02 socat[3808469] E connect(5, AF=2 127.0.0.1:11222, 16): Connection refused
```

if Quarkus tries to inject the remote cache manager

```
2020-07-08 18:53:03,309 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:155)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:301)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:42)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:126)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:56)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:521)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error injecting org.infinispan.client.hotrod.RemoteCacheManager it.targz.InfinispanClientApp.cacheManager
	at it.targz.InfinispanClientApp_Bean.create(InfinispanClientApp_Bean.zig:315)
	at it.targz.InfinispanClientApp_Bean.create(InfinispanClientApp_Bean.zig:338)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at it.targz.InfinispanClientApp_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(InfinispanClientApp_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:135)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:77)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:444)
	... 12 more
Caused by: org.infinispan.client.hotrod.exceptions.TransportException:: org.infinispan.client.hotrod.exceptions.TransportException:: ISPN004071: Connection to 127.0.0.1/127.0.0.1:11222 was closed while waiting for response.
	at org.infinispan.client.hotrod.impl.transport.netty.ActivationHandler.exceptionCaught(ActivationHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.lambda$channelActive$2(AuthHandler.java:87)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.infinispan.client.hotrod.impl.operations.HotRodOperation.channelInactive(HotRodOperation.java:108)
	at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.channelInactive(HeaderDecoder.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: org.infinispan.client.hotrod.exceptions.TransportException:: ISPN004071: Connection to 127.0.0.1/127.0.0.1:11222 was closed while waiting for response.
	... 23 more
```

Environment:

```
$ uname -a                   
Linux x1 5.7.7-200.fc32.x86_64 #1 SMP Wed Jul 1 19:53:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ oc version                        
Client Version: openshift-clients-4.4.0-202006211643.p0-2-gd89e458c3
Server Version: 4.4.11
Kubernetes Version: v1.17.1+166b070
```
```
$ java -version   
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode, sharing)
```

**Comment by j1cken** [comment]
11222 is listening on the pod ip

```
11:52:50,513 INFO  (ForkJoinPool.commonPool-worker-3) [org.infinispan.SERVER] ISPN080018: Protocol HotRod (internal)
11:52:51,141 INFO  (main) [org.infinispan.SERVER] ISPN080018: Protocol REST (internal)
11:52:51,827 INFO  (main) [org.infinispan.SERVER] ISPN080004: Protocol SINGLE_PORT listening on 10.131.0.10:11222
11:52:51,827 INFO  (main) [org.infinispan.SERVER] ISPN080034: Server 'datagrid-0-40591' listening on http://10.131.0.10:11222
11:52:51,827 INFO  (main) [org.infinispan.SERVER] ISPN080001: Red Hat Data Grid Server 8.0.1.GA started in 27905ms
11:54:59,939 INFO  (jgroups-7,datagrid-0-40591) [org.infinispan.CLUSTER] ISPN000094: Received new cluster view for channel infinispan: [datagrid-0-40591|1] (2) [datagrid-0-40591, datagrid-1-1367]
11:54:59,945 INFO  (jgroups-7,datagrid-0-40591) [org.infinispan.CLUSTER] ISPN100000: Node datagrid-1-1367 joined the cluster
```

**Comment by dmvolod** [comment]
@j1cken it's expected behavior as described here https://github.com/kubernetes/kubernetes/issues/72597
Infinispan server accept connections only on specific IP as you can see in the log, but kubectl port-forward connect to the loopback remote interface only. we can't change accepted interface as it not customizable on the server image level.

**Comment by j1cken** [comment]
Thx, @dmvolod.

```
#
# Sets the host name/port to connect to. Each one is separated by a semicolon (eg. host1:11222;host2:11222).
#
#quarkus.infinispan-client.server-list=
```

I don't think there are much options left ... except running a local container meanwhile :/ and wait for the issue to be fixed.
I'll reach out to the Quarkus guys to see if they can think of something else.

```
$ grep infinispan src/main/resources/application.properties.example
#quarkus.infinispan-client.auth-callback-handler=
#quarkus.infinispan-client.auth-client-subject=
#quarkus.infinispan-client.auth-password=
#quarkus.infinispan-client.auth-realm=
#quarkus.infinispan-client.auth-server-name=
#quarkus.infinispan-client.auth-username=
#quarkus.infinispan-client.client-intelligence=
#quarkus.infinispan-client.near-cache-max-entries=0
#quarkus.infinispan-client.sasl-mechanism=
#quarkus.infinispan-client.server-list=
#quarkus.infinispan-client.use-auth=
```

**Comment by dmvolod** [comment]
@j1cken I'm not sure, need to validate, but NodePort or LoadBalancer should work. The upcoming release 8.1 will support Route and Ingress. You can validate these options at the upstream 2.0.1 version.
@Crumby , do you have any other idea how to connect from the Quarkus?

**Comment by j1cken** [comment]
@dmvolod I have no doubt I can make it working somehow, but ... I'm thinking of (better like) an "average" developer who just wants to develop with Quarkus against Infinispan. I don't want them to look for someone to open up firewalls for node ports, have port forwarding somehow, have loadbalancers, have them even knowing about node ports, finding someone with cluster-admin privs to do all the changes for them, etc. IMHO these should be basic features. I - as a developer - would expect them to just work. Developers want an easy life! If it's not easy, they just don't use it. Does that make sense?

Route/Ingress sounds promising. We just need to make Quarkus aware of it or even utilize it.

**Comment by dmvolod** [comment]
Yes, @j1cken sure, I've created an issue in the infinispan/infinispan-images repo and developers plant to be fixed infinispan.bind.address in 11.0.2

**Comment by j1cken** [comment]
@dmvolod awesome, thx!

**Comment by dmvolod** [comment]
@j1cken could you please to try with an `infinispan/server:11.0.3.Final` image and ExtraJvmOpts set to 
`-Dinfinispan.bind.address=0.0.0.0`

**Comment by j1cken** [comment]
LGTM

I have been using the native 11.0.3-Final image without "-b 0.0.0.0" on OpenShift:

```
quay.io/repository/infinispan/server-native@sha256:6c8eb66954639254e6abc6f8629b5af187cc915f9334c883d7bf32e63270f11b
```
```
$ oc port-forward svc/jdg 11222
Forwarding from 127.0.0.1:11222 -> 11222
Forwarding from [::1]:11222 -> 11222
Handling connection for 11222
```

server.log
```
2020-08-07 13:48:01,713 INFO  [org.inf.SERVER] (main) ISPN080004: Protocol SINGLE_PORT listening on 127.0.0.1:11222
2020-08-07 13:48:01,713 INFO  [org.inf.SERVER] (main) ISPN080034: Server 'jdg-6-svbws-63079' listening on http://127.0.0.1:11222
```

Quarkus is now able to inject the RemoteCacheManager on StartupEvent with
```
%dev.quarkus.infinispan-client.server-list = 127.0.0.1:11222
```
using quarkus:dev.

Thx a lot!

**Comment by j1cken** [comment]
REST API working as well

create cache:
```
$ curl -XPOST -d "<infinispan><cache-container><invalidation-cache name=\"testcache\" mode=\"ASYNC\" statistics=\"true\"/></cache-container></infinispan>" -H "Content-type:application/xml" 'infinispan:pwd@localhost:11222/rest/v2/caches/testcache'
```
create key:
```
$ curl -XPOST -d "bar" 'infinispan:pwd@localhost:11222/rest/v2/caches/testcache/foo'
```
get value:
```
curl -i "infinispan:pwd@localhost:11222/rest/v2/caches/testcache/foo"
HTTP/1.1 200 OK
Etag: -393671897
Content-Type: application/octet-stream
connection: keep-alive
content-length: 3

bar%         
```

**Comment by dmvolod** [comment]
Thanks for providing info, @j1cken 
I'm closing the issue now

**Comment by dmvolod** [comment]
@j1cken please note, that bind on 127.0.0.1 for native image is regression and will be fixed in https://github.com/infinispan/infinispan-images/issues/91
