### ISSUE TITLE
Infinispan cluster can't WellFormed using 12.0.0.CR1 image on k8s/TravisCI

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-operator#716]
OCP works fine with 12.0.0.CR1 image
Rolling back TravisCI back to 12.0.0.Dev07 temporary

**Comment by ryanemerson** [comment]
Travis has been failing consistently  on master since before CR1 was released. Is the issue really with the CR1 distribution?

**Comment by dmvolod** [comment]
Yes, @ryanemerson . It could be failed sometimes, but now every build is failed
Fixing version to 12.0.0.Dev07 is resolving fails build. Stable failing become 12 days ago, when CR1 was released

**Comment by ryanemerson** [comment]
Stack trace from failed cluster
```
11:59:41,220 INFO  (jgroups-7,test-backup-restore-data-grid-source-0-8893) [org.infinispan.CLUSTER] ISPN100001: Node test-backup-restore-data-grid-source-1-39638 left the cluster
11:59:41,231 WARN  (non-blocking-thread--p2-t2) [org.infinispan.topology.ClusterTopologyManagerImpl] ISPN000196: Failed to recover cluster state after the current node became the coordinator (or after merge), will retry org.infinispan.remoting.RemoteException: ISPN000217: Received exception from test-backup-restore-data-grid-source-0-8893, see cause for remote stack trace
    at org.infinispan.remoting.transport.ResponseCollectors.wrapRemoteException(ResponseCollectors.java:25)
    at org.infinispan.topology.ClusterTopologyManagerImpl$CacheStatusResponseCollector.addException(ClusterTopologyManagerImpl.java:363)
    at org.infinispan.topology.ClusterTopologyManagerImpl$CacheStatusResponseCollector.addException(ClusterTopologyManagerImpl.java:317)
    at org.infinispan.remoting.transport.ValidResponseCollector.addResponse(ValidResponseCollector.java:29)
    at org.infinispan.topology.TopologyManagementHelper.lambda$addLocalResult$2(TopologyManagementHelper.java:129)
    at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
    at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
    at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
    at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:143)
    at org.infinispan.topology.TopologyManagementHelper.lambda$addLocalResult$3(TopologyManagementHelper.java:125)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
    at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
    at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
    at org.infinispan.topology.TopologyManagementHelper.addLocalResult(TopologyManagementHelper.java:125)
    at org.infinispan.topology.TopologyManagementHelper.executeOnClusterSync(TopologyManagementHelper.java:56)
    at org.infinispan.topology.ClusterTopologyManagerImpl.fetchClusterStatus(ClusterTopologyManagerImpl.java:554)
    at org.infinispan.topology.ClusterTopologyManagerImpl.recoverClusterStatus(ClusterTopologyManagerImpl.java:426)
    at org.infinispan.topology.ClusterTopologyManagerImpl.lambda$handleClusterView$4(ClusterTopologyManagerImpl.java:391)
    at org.infinispan.util.concurrent.ActionSequencer.safeNonBlockingCall(ActionSequencer.java:57)
    at org.infinispan.util.concurrent.ActionSequencer.access$400(ActionSequencer.java:32)
    at org.infinispan.util.concurrent.ActionSequencer$SequenceEntry.run(ActionSequencer.java:226)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from test-backup-restore-data-grid-source-0-8893, see cause for remote stack trace
    at org.infinispan.topology.TopologyManagementHelper.makeResponse(TopologyManagementHelper.java:138)
    at org.infinispan.topology.TopologyManagementHelper.lambda$addLocalResult$2(TopologyManagementHelper.java:126)
    ... 19 more
Caused by: org.infinispan.commons.IllegalLifecycleStateException: Cannot wire or start components while the registry is not running
    at org.infinispan.factories.impl.BasicComponentRegistryImpl.prepareWrapperChange(BasicComponentRegistryImpl.java:678)
    at org.infinispan.factories.impl.BasicComponentRegistryImpl.wireWrapper(BasicComponentRegistryImpl.java:208)
    at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$1000(BasicComponentRegistryImpl.java:30)
    at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.wire(BasicComponentRegistryImpl.java:809)
    at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:785)
    at org.infinispan.factories.GlobalComponentRegistry.getLocalTopologyManager(GlobalComponentRegistry.java:374)
    at org.infinispan.commands.topology.CacheStatusRequestCommand.invokeAsync(CacheStatusRequestCommand.java:34)
    at org.infinispan.topology.TopologyManagementHelper.invokeAsync(TopologyManagementHelper.java:151)
    at org.infinispan.topology.TopologyManagementHelper.executeOnClusterSync(TopologyManagementHelper.java:51)
    ... 9 more
11:59:41,244 INFO  (Thread-0) [org.infinispan.CLUSTER] ISPN000080: Disconnecting JGroups channel test-backup-restore-data-grid-source
11:59:41,320 INFO  (Thread-0) [org.infinispan.CONTAINER] ISPN000390: Persisted state, version=12.0.0.CR1 timestamp=2020-12-23T11:59:41.319740Z
11:59:41,323 INFO  (Thread-0) [org.infinispan.SERVER] ISPN080003: Infinispan Server stopped
*** Server process (85) received TERM signal ***
```

**Comment by ryanemerson** [comment]
I am able to reproduce locally with minikube. `TestClusterFormation` consistently fails for me

**Comment by dmvolod** [comment]
Reproduced on OCP with detailed error message from REST API
```
Errors: example-infinispan-0: unable to decode: invalid character 'I' looking for beginning of value,example-infinispan-1: unable to decode: invalid character 'I' looking for beginning of value Views: 
```

**Comment by dmvolod** [comment]
Closing as digest authentication is now used #727
